version: "2.4"  #check version
services:
  db:
    image: datajoint/mysql:5.7 
    container_name: vr4mice_db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=simple
    volumes:
      - /mnt/md0/vr4mice_database/database:/var/lib/mysql
  app:
    image: "vr4mice_app"
    container_name: vr4mice
    build:
      context: .
      dockerfile: docker/client/Dockerfile
      args:
        - user
        - usern
    network_mode: host
    #depends_on:
    #    - db
    volumes:
        - "./:/app"
          #- "/shared:/shared"
          #  - "/mnt/md0/vr4mice_database/data:/storage"
    working_dir: /app
    environment:
      - DJ_HOST="127.0.0.1"
      - DJ_USER=root
      - DJ_PWD=simple
      - DJ_SUPPORT_FILEPATH_MANAGEMENT=TRUE
      - DJ_SUPPORT_ADAPTED_TYPES=TRUE
      - STORAGE="/storage"
    stdin_open: true
    tty: true
