version: "2.4"  #check version
services:
  db:
    image: datajoint/mysql:5.7 
    container_name: vr4mice_db
    ports:
<<<<<<< HEAD
            - "128.178.51.114:3309:3306"
=======
            - "127.0.0.1:3306"
>>>>>>> d26926711dc1258908d734b2b3bc044a905a1879
    environment:
      - MYSQL_ROOT_PASSWORD=simple
    volumes:
      - /mnt/database/vr4mice/vr4mice_database/database/:/var/lib/mysql
  client:
    image: "vr4mice_app"
    container_name: vr4mice
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - user
        - usern
    network_mode: host
    volumes:
        - "./:/app"
        - "/shared:/shared"

        - "/mnt/database/vr4mice/vr4mice_database/data:/data"

        - "./base/base_min_schemas:/base_schemas"
        - "./base/base_actions:/base_actions"

    working_dir: /app
    env_file:
        - .env
    stdin_open: true
    tty: true
