version: "2.4"  #check version
services:
  db:
    image: datajoint/mysql:5.7 
    container_name: vr4mice_db
    ports:
            - "128.178.51.167:3309:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=simple
    volumes:
      - /mnt/database/vr4mice/vr4mice_database/database/:/var/lib/mysql
  client:
    image: "vr4mice_app"
    container_name: vr4mice
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - user
        - usern
    #network_mode: host
    volumes:
        - "./:/app"
        - "/shared:/shared"

        - "/mnt/database/vr4mice/vr4mice_database/data:/data"

        - "./base/base_min_schemas:/base_schemas"
        - "./base/base_actions:/base_actions"
    ports: 
        - 8887:8888

    working_dir: /app
    env_file:
        - .env
    stdin_open: true
    tty: true

  aws_sync:
      image: "mysql:sync"
      container_name: aws_sync
      build:
        context: .
        dockerfile: DockerfileSync
        args:
           - user
           - usern
           - mysql_config
      network_mode: host
      volumes:
       - ./logs:/logs
       - ./backup:/app
      working_dir: /app
      stdin_open: true
      tty: true
