services:
  trainer:
    image: ${USER}_rl-project-ar:1.0
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ${VR4MICE_PATH}:/app
    tty: true
    stdin_open: true
    deploy:
      resources:
        limits:
          memory: 12G
        reservations:
          devices:
            # Gives access to all available GPUs
            - driver: nvidia
              count: all
              capabilities: [ "gpu" ]
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL

  developer:
    image: ${USER}_rl-project-ar:1.0
    container_name: user_${USER}_AR_developer
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ${VR4MICE_PATH}:/app
    tty: true
    stdin_open: true
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 4G
        reservations:
          devices:
            # Gives access to all available GPUs
            - driver: nvidia
              count: all
              capabilities: [ "gpu" ]
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
