from .mouse_manual_water import ManualWater

from .mouse_detection_p1 import DetectionWithoutVelocityThresholdTask
from .mouse_detection_p2 import DetectionWithVelocityThresholdTask
from .mouse_discrim import DiscriminationTask
from .mouse_discrim_occluders import DiscriminationWithOccludersTask
from .mouse_discrim_multioccluders import DiscriminationWithMultiOccludersTask

from .mouse_detection_p1_inv import InvDetectionNoVelThrTask
from .mouse_detection_p2_inv import InvDetectionVelThrTask
from .mouse_discrim_inv import InvDiscrimTask
from .mouse_discrim_occluders_inv import InvDiscrimOccludersTask
from .mouse_discrim_multioccluders_inv import InvDiscrimMultiOccludersTask

from .mouse_shape_detection_p1 import ShapeDetectionWithoutVelocityThresholdTask
from .mouse_shape_detection_p2 import ShapeDetectionWithVelocityThresholdTask
from .mouse_shape_discrim import ShapeDiscrim
from .mouse_shape_discrim_occluders import ShapeDiscrimOccluders
from .mouse_shape_discrim_narrow_occluders import ShapeDiscrimNarrowOccluders
from .mouse_shape_discrim_multioccluders import ShapeDiscrimMultiOccluders