class_name: InvShapeDisMultiOccludersTask
description: |
  Shape discrimination task, with occluders of different sizes
  The mouse must report the location of the black teardrop object and ignore the wide Pacman.

# Only the parameters that differ from configs/common.yaml.
params:
  session_label:
  - ar_shape_discrim_multi_occluders_inv
  epoch_labels:
  - teardrop_vs_pacman
  slit_size:
  - 12.0
  - 8.48
  - 6.0
  - 4.2
  - 3
  slit_depth: 0.02
  target_selection: 5.0
  distractor_selection: 11.0
  occlusion_type: 1.0
  target_rotation: 15.0
  target_spread: 3.0
  target_distance: 4.0
