class_name: InvShapeDisTask
description: |
  Discrimination for shape task,with velocity threshold for trial initiation, no occluders.
  The mouse must report the location of the black teardrop object and ignore the wide Pacman.

# Only the parameters that differ from configs/common.yaml.
params:
  session_label:
  - ar_shape_discrimination_inv
  epoch_labels:
  - teardrop_vs_pacman
  slit_size:
  - 4.0
  - 4.0
  - 1
  slit_depth: 0.02
  target_selection: 5.0
  distractor_selection: 11.0
  target_rotation: 15.0
  target_spread: 3.0
  target_distance: 4.0
