class_name: DiscriminationWithOccludersTask
description: |
  Discrimination task with occluders on.

# Only the parameters that differ from configs/common.yaml.
params:
  session_label:
  - ar_discrim_occluders
  slit_size:
  - 4.3
  - 12.0
  - 2
  occlusion_type: 1.0
